use crate as bevy_rblx;
use bevy_rblx::core::LuaSingleton;

bevy_rblx_derive::create_enums!([
    AnimatorRetargetingMode,
    AvatarUnificationMode,
    Axis,
    ClientAnimatorThrottlingMode,
    CreatorType,
    FluidForces,
    IKControlConstraintSupport,
    MeshPartHeadsAndAccessories,
    MessageType,
    ModelLevelOfDetail,
    ModelStreamingBehavior,
    ModelStreamingMode,
    MoverConstraintRootBehaviorMode,
    NormalId,
    PathfindingUseImprovedSearch,
    PhysicsSteppingMethod,
    PlayerCharacterDestroyBehavior,
    PrimalPhysicsSolver,
    RejectCharacterDeletions,
    RenderingCacheOptimizationMode,
    ReplicateInstanceDestroySetting,
    RollOutState,
    RotationOrder,
    RunContext,
    RunState,
    SandboxedInstanceMode,
    SecurityCapability,
    SignalBehavior,
    StreamOutBehavior,
    StreamingIntegrityMode
]);
